package markdown

import (
	"os"
	"regexp"
	"slices"
	"strings"
	"testing"
	"unicode"

	"charm.land/lipgloss/v2"

	"git.bobparsons.dev/deadstyle/lazyforge/internal/ui/style"
)

var ansiRE = regexp.MustCompile(`\x1b\[[0-9;]*m|\x1b\]8;;[^\x1b]*\x1b\\`)

func strip(s string) string { return ansiRE.ReplaceAllString(s, "") }

const renovateBody = "This PR contains the following updates:\n\n" +
	"| Package | Update | Change |\n|---|---|---|\n" +
	"| [ghcr.io/gtsteffaniak/filebrowser](https://github.com/gtsteffaniak/filebrowser) | patch | `1.5.6-stable` → `1.5.8-stable` |\n\n" +
	"---\n\n### Configuration\n\n📅 **Schedule**: (in timezone America/Chicago)\n\n- Branch creation\n  - Between 12:00 AM and 05:59 AM, only on Monday\n- Automerge\n  - At any time\n\n" +
	"- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\n---\n\n" +
	"This PR has been generated by [Mend Renovate CLI](https://github.com/renovatebot/renovate).\n\n<!--renovate-debug:eyJjcmVhdGVk-->\n"

func TestImagesFindsOnlyBlockImages(t *testing.T) {
	tests := []struct {
		name, body string
		want       []string
	}{
		{"image inside text", "see ![a](x.png) here", nil},
		{"list item", "- ![a](x.png)", nil},
		{"blockquote", "> ![a](x.png)", nil},
		{"table cell", "| h |\n|---|\n| ![a](x.png) |", nil},
		{"html img block", "<img src=x.png>", nil},
		{"html img inside text", "para <img src=x.png>", nil},
		{"raw html after the image", "![a](x.png)<br>", nil},
		{"link-wrapped image", "[![a](x.png)](https://e)", []string{"x.png"}},
		{"deduplicated in first-seen order", "![a](x.png) ![b](y.png)\n\n![c](x.png)", []string{"x.png", "y.png"}},
		{"soft break keeps both", "![a](x.png)\n![b](y.png)", []string{"x.png", "y.png"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Images(tt.body)
			if tt.want == nil && got != nil {
				t.Fatalf("Images = %q, want nil", got)
			}
			if !slices.Equal(got, tt.want) {
				t.Fatalf("Images = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRenderWithImagesSplicesBlockImage(t *testing.T) {
	const body = "intro\n\n![shot](/attachments/x.png)\n\noutro"
	if got := Images(body); !slices.Equal(got, []string{"/attachments/x.png"}) {
		t.Fatalf("Images = %q", got)
	}
	blocks := map[string][]string{"/attachments/x.png": {"ROW0", "ROW1"}}
	got := RenderWithImages(body, 40, blocks)
	if !strings.Contains(got, "ROW0\nROW1") {
		t.Fatalf("spliced rows are not consecutive lines:\n%s", strip(got))
	}
	lines := strings.Split(strip(got), "\n")
	for i := range lines {
		lines[i] = strings.TrimSpace(lines[i])
	}
	i := slices.Index(lines, "ROW0")
	if i < 2 || i+3 >= len(lines) {
		t.Fatalf("spliced rows sit at line %d of %d:\n%s", i, len(lines), strip(got))
	}
	if lines[i-2] != "intro" || lines[i-1] != "" || lines[i+2] != "" || lines[i+3] != "outro" {
		t.Errorf("neighbours of the spliced rows are wrong:\n%s", strip(got))
	}
	if strings.Contains(strip(got), "shot") {
		t.Errorf("the link line survived the splice:\n%s", strip(got))
	}
}

func TestRenderWithImagesNilAndEmptyMatchRender(t *testing.T) {
	notes, err := os.ReadFile("testdata/release-notes.md")
	if err != nil {
		t.Fatal(err)
	}
	for _, body := range []string{renovateBody, string(notes), "intro ![a](x.png) outro", "- ![a](x.png)"} {
		want := Render(body, 60)
		if got := RenderWithImages(body, 60, nil); got != want {
			t.Errorf("nil blocks changed the output:\n got %q\nwant %q", got, want)
		}
		if got := RenderWithImages(body, 60, map[string][]string{}); got != want {
			t.Errorf("empty blocks changed the output:\n got %q\nwant %q", got, want)
		}
	}
}

func TestRenderWithImagesIgnoresNonBlockDestinations(t *testing.T) {
	blocks := map[string][]string{"x.png": {"SPLICED"}}
	for _, body := range []string{"see ![a](x.png) here", "- ![a](x.png)", "| h |\n|---|\n| ![a](x.png) |"} {
		if got, want := RenderWithImages(body, 60, blocks), Render(body, 60); got != want {
			t.Errorf("%q changed with a block for its destination:\n got %q\nwant %q", body, got, want)
		}
	}
}

func TestRenderWithImagesStacksUnitsOfOneParagraph(t *testing.T) {
	blocks := map[string][]string{"x.png": {"L1", "L2"}}
	got := strip(RenderWithImages("![a](x.png) ![b](y.png)", 60, blocks))
	lines := strings.Split(got, "\n")
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " ")
	}
	i := slices.Index(lines, "L1")
	if i < 0 || i+2 >= len(lines) || lines[i+1] != "L2" || !strings.Contains(lines[i+2], "🖼 b") {
		t.Fatalf("the spliced unit is not followed directly by the second unit's link:\n%s", got)
	}
	if strings.Contains(got, "🖼 a") {
		t.Errorf("the spliced unit still shows its link:\n%s", got)
	}
}

func TestRenderWithImagesSplicedLinesCarryNoLink(t *testing.T) {
	got := RenderWithImages("[![a](/x.png)](https://e.example/page)", 60, map[string][]string{"/x.png": {"L1"}})
	if !strings.Contains(got, "L1") {
		t.Fatalf("the spliced line is missing:\n%q", got)
	}
	if strings.Contains(got, "e.example") {
		t.Errorf("the spliced line links to the image's wrapper:\n%q", got)
	}
}

func TestRenderWithImagesKeepsSplicedLinesInWidth(t *testing.T) {
	const width = 20
	blocks := map[string][]string{"/x.png": {strings.Repeat("W", 60)}}
	for i, l := range strings.Split(RenderWithImages("![a](/x.png)", width, blocks), "\n") {
		if w := lipgloss.Width(l); w > width {
			t.Errorf("line %d is %d wide at width %d: %q", i, w, width, strip(l))
		}
	}
}

func TestRenderFitsEveryWidth(t *testing.T) {
	notes, err := os.ReadFile("testdata/release-notes.md")
	if err != nil {
		t.Fatal(err)
	}
	for name, body := range map[string]string{"renovate": renovateBody, "release notes": string(notes)} {
		for _, w := range []int{20, 40, 60, 80, 100} {
			for i, l := range strings.Split(Render(body, w), "\n") {
				if lipgloss.Width(l) > w {
					t.Errorf("%s at %d: line %d is %d wide: %q", name, w, i, lipgloss.Width(l), strip(l))
				}
			}
		}
	}
}

func TestRenderDropsHTMLAndKeepsLinkText(t *testing.T) {
	got := Render(renovateBody, 80)
	text := strip(got)
	for _, gone := range []string{"renovate-debug", "rebase-check", "<!--", "https://github.com/renovatebot", "](", "**"} {
		if strings.Contains(text, gone) {
			t.Errorf("output still contains %q:\n%s", gone, text)
		}
	}
	if !strings.Contains(text, "Mend Renovate CLI") || !strings.Contains(text, "If you want to rebase/retry this PR") {
		t.Errorf("link text or task text missing:\n%s", text)
	}
}

func TestRenderLinksAreHyperlinks(t *testing.T) {
	got := Render("see [the docs](https://example.com/docs) now", 80)
	if !strings.Contains(got, "\x1b]8;;https://example.com/docs\x1b\\") || !strings.Contains(got, "\x1b]8;;\x1b\\") {
		t.Fatalf("no OSC 8 hyperlink in %q", got)
	}
}

func TestRenderLinkWrappedAcrossLinesStaysLinked(t *testing.T) {
	got := Render("[one two three four](https://example.com)", 9)
	if n := strings.Count(got, "\x1b]8;;https://example.com\x1b\\"); n < 2 {
		t.Fatalf("each wrapped piece should carry the link, got %d in %q", n, got)
	}
}

func TestRenderTableFitsAsColumns(t *testing.T) {
	got := strip(Render("| A | B |\n|---|---|\n| one | two |\n", 40))
	lines := strings.Split(got, "\n")
	if len(lines) != 3 || !strings.Contains(lines[0], "A") || !strings.Contains(lines[1], "┼") || !strings.Contains(lines[2], "one") {
		t.Fatalf("table:\n%s", got)
	}
}

func TestRenderWideTableStacks(t *testing.T) {
	got := strip(Render(renovateBody, 40))
	for _, want := range []string{"Package: ghcr.io/gtsteffaniak/filebrowser", "Update: patch", "Change: 1.5.6-stable → 1.5.8-stable"} {
		if !strings.Contains(strings.ReplaceAll(got, "\n", " "), want) {
			t.Errorf("stacked table missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "┼") {
		t.Errorf("table should have stacked at 40 columns:\n%s", got)
	}
}

func TestRenderTaskAndListMarkers(t *testing.T) {
	got := strip(Render("- [ ] todo\n- [x] done\n- plain\n\n1. first\n2. second\n", 40))
	for _, want := range []string{"☐ todo", "☑ done", "• plain", "1. first", "2. second"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
}

func TestRenderNestedListIndents(t *testing.T) {
	lines := strings.Split(strip(Render("- a\n  - b\n", 40)), "\n")
	if len(lines) != 2 || lines[0] != "• a" || lines[1] != "  • b" {
		t.Fatalf("nested list: %q", lines)
	}
}

func TestRenderEmptyBody(t *testing.T) {
	if got := Render("", 40); got != "" {
		t.Fatalf("Render(\"\") = %q", got)
	}
}

func TestRenderDecodesEscapesAndEntities(t *testing.T) {
	got := strip(Render("foo\\_bar and 1 &lt; 2 &amp; &#8203;x", 80))
	for _, want := range []string{"foo_bar", "1 < 2 &", "\u200bx"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %q", want, got)
		}
	}
	if strings.Contains(got, "\\") || strings.Contains(got, "&lt;") {
		t.Errorf("undecoded text in %q", got)
	}
}

func TestRenderOnlyLinksSafeSchemes(t *testing.T) {
	for _, u := range []string{"javascript:alert(1)", "JavaScript:alert(1)", "file:///etc/passwd", "relative/path", "#anchor"} {
		got := Render("[x]("+u+")", 80)
		if strings.Contains(got, "\x1b]8;") {
			t.Errorf("%q became a hyperlink: %q", u, got)
		}
		if !strings.Contains(strip(got), "x") {
			t.Errorf("%q lost its text: %q", u, got)
		}
	}
	for _, u := range []string{"http://a.com", "HTTPS://a.com", "mailto:a@b.com"} {
		if got := Render("[x]("+u+")", 80); !strings.Contains(got, "\x1b]8;;"+u+"\x1b\\") {
			t.Errorf("%q isn't a hyperlink: %q", u, got)
		}
	}
}

func TestRenderStripsControlCharacters(t *testing.T) {
	got := Render("a\x1b]52;c;x\x07b \x1b[31mred &#27;[2Jz\x7f", 80)
	for _, bad := range []string{"\x1b]52", "\x07", "\x1b[31m", "\x7f", "\x1b[2J"} {
		if strings.Contains(got, bad) {
			t.Errorf("control sequence %q reached the output: %q", bad, got)
		}
	}
	if raw := strings.ReplaceAll(strip(got), "\x1b", "<ESC>"); strings.Contains(raw, "<ESC>") {
		t.Errorf("stray escape in %q", raw)
	}
}

func TestRenderImageInLinkKeepsLinkURL(t *testing.T) {
	got := Render("[![badge](https://img.example/b.png)](https://target.example)", 80)
	if !strings.Contains(got, "\x1b]8;;https://target.example\x1b\\") || strings.Contains(got, "img.example") {
		t.Fatalf("image should link to the enclosing target: %q", got)
	}
	if got := Render("![alt](https://img.example/b.png)", 80); !strings.Contains(got, "https://img.example/b.png") || !strings.Contains(strip(got), "🖼 alt") {
		t.Fatalf("bare image: %q", got)
	}
}

func TestRenderBrIsHardBreak(t *testing.T) {
	for _, br := range []string{"<br>", "<br/>", "<br />", "<BR>"} {
		lines := strings.Split(strip(Render("one"+br+"two", 80)), "\n")
		if len(lines) != 2 || lines[0] != "one" || lines[1] != "two" {
			t.Errorf("%s: %q", br, lines)
		}
	}
	if got := strip(Render("a <span>b</span> c", 80)); got != "a b c" {
		t.Errorf("other raw HTML should drop: %q", got)
	}
}

func TestRenderKeepsSummaryText(t *testing.T) {
	body := "<details><summary>actions/checkout (actions/checkout)</summary>\n\n### v4.2.0\n\nnotes\n\n</details>\n"
	got := Render(body, 80)
	plain := strip(got)
	if !strings.HasPrefix(plain, "actions/checkout (actions/checkout)") || !strings.Contains(plain, "notes") {
		t.Fatalf("summary missing:\n%s", plain)
	}
	if strings.Contains(plain, "<") {
		t.Errorf("tags leaked:\n%s", plain)
	}
	if !strings.Contains(got, style.Heading.Render("actions/checkout")) {
		t.Errorf("summary isn't heading-styled: %q", got)
	}
}

func TestWrapKeepsGluedAtomsTogether(t *testing.T) {
	for w := 8; w < 30; w++ {
		for _, l := range strings.Split(strip(Render("aaaa bbbb [link](https://x.com). **foo**bar `code`, end", w)), "\n") {
			if strings.HasPrefix(l, ".") || strings.HasPrefix(l, ",") || strings.HasPrefix(l, "bar") {
				t.Errorf("width %d: line starts with detached punctuation: %q", w, l)
			}
		}
	}
}

func TestRenderNoDoubleBlankLines(t *testing.T) {
	got := Render("one\n\n#\n\n<br>\n\ntwo\n", 40)
	if strings.Contains(got, "\n\n\n") {
		t.Errorf("empty heading left a double blank: %q", got)
	}
	if wrap(nil, 10) != nil {
		t.Error("wrap of no atoms should be nil")
	}
}

func TestRenderNeverWiderThanTinyWidths(t *testing.T) {
	body := "- item one\n  - nested **bold** item\n\n> quote text\n>\n> more\n\n```\nlong code line here\n```\n\n漢字漢字漢字 😀😀😀\n\n| a | b |\n|---|---|\n| [x](https://x.com) | `y` |\n\n- [ ] task text here\n"
	for _, w := range []int{1, 2, 3, 5} {
		for i, l := range strings.Split(Render(body, w), "\n") {
			if lipgloss.Width(l) > w {
				t.Errorf("width %d line %d is %d wide: %q", w, i, lipgloss.Width(l), strip(l))
			}
		}
	}
}

func TestRenderCodeBlockWrapsLongLines(t *testing.T) {
	got := Render("```\nabcdefghijklmnopqrstuvwxyz\n```", 12)
	if strings.Contains(strip(got), "…") {
		t.Errorf("code was cut: %q", got)
	}
	lines := strings.Split(strip(got), "\n")
	var joined string
	for _, l := range lines {
		joined += strings.TrimPrefix(l, "  ")
	}
	if len(lines) < 3 || joined != "abcdefghijklmnopqrstuvwxyz" {
		t.Errorf("code didn't wrap losslessly: %q", lines)
	}
	if !strings.Contains(got, style.Code.Render("  abcdefghij")) {
		t.Errorf("code lines aren't code-styled: %q", got)
	}
}

func TestRenderTableCellsKeepInlineStyle(t *testing.T) {
	body := "| Name | Link |\n|---|---|\n| `code` **b** | [docs](https://example.com) |\n"
	for _, w := range []int{60, 12} {
		got := Render(body, w)
		if !strings.Contains(got, "\x1b]8;;https://example.com\x1b\\") {
			t.Errorf("width %d: cell link isn't clickable: %q", w, got)
		}
		if !strings.Contains(got, style.Code.Render("code")) || !strings.Contains(got, style.Text.Bold(true).Render("b")) {
			t.Errorf("width %d: cell lost code/bold style: %q", w, got)
		}
	}
	if strings.Contains(strip(Render(body, 60)), "Name: ") || !strings.Contains(strip(Render(body, 12)), "Name: ") {
		t.Error("expected fitted layout at 60 and stacked at 12")
	}
}

func TestRenderTaskItemContinuationIndents(t *testing.T) {
	lines := strings.Split(strip(Render("- [ ] one two three four five\n  - nested\n", 14)), "\n")
	if lines[0] != "☐ one two" || lines[1] != "  three four" {
		t.Fatalf("task wrap: %q", lines)
	}
	if lines[len(lines)-1] != "  • nested" {
		t.Fatalf("nested under task: %q", lines)
	}
}

func TestRenderQuoteBlankLineHasNoTrailingSpace(t *testing.T) {
	lines := strings.Split(strip(Render("> a\n>\n> b", 40)), "\n")
	if len(lines) != 3 || lines[0] != "│ a" || lines[1] != "│" || lines[2] != "│ b" {
		t.Fatalf("quote: %q", lines)
	}
}

func TestRenderInlineStyles(t *testing.T) {
	got := Render("**bold** and *it*", 80)
	if !strings.Contains(got, style.Text.Bold(true).Render("bold")) || !strings.Contains(got, style.Text.Italic(true).Render("it")) {
		t.Errorf("bold/italic not styled: %q", got)
	}
}

func TestRenderBlockStyles(t *testing.T) {
	got := Render("# Title\n\n---\n\n> quoted\n\n```\ncode\n```", 20)
	if !strings.Contains(got, style.Heading.Render("Title")) {
		t.Errorf("heading not styled: %q", got)
	}
	if !strings.Contains(got, style.Faint.Render(strings.Repeat("─", 20))) {
		t.Errorf("thematic break missing: %q", got)
	}
	if !strings.Contains(strip(got), "│ quoted") {
		t.Errorf("quote prefix missing: %q", strip(got))
	}
	if !strings.Contains(got, style.Code.Render("  code")) {
		t.Errorf("fenced code not styled: %q", got)
	}
}

func TestRenderKeepsTextInsideHTMLBlocks(t *testing.T) {
	got := strip(Render("<div>\nhello **world**\n</div>\n\nafter", 40))
	if !strings.Contains(got, "hello") || !strings.Contains(got, "after") || strings.Contains(got, "<div>") {
		t.Fatalf("html block text lost or tags leaked: %q", got)
	}
}

func TestRenderWideHeaderOnlyTableStillShowsHeaders(t *testing.T) {
	got := strip(Render("| Package | Update |\n|---|---|\n", 7))
	if !strings.Contains(strings.ReplaceAll(got, "\n", ""), "Package") {
		t.Fatalf("headers lost: %q", got)
	}
}

func TestRenderStripsEscapesFromEveryInlineSource(t *testing.T) {
	for name, body := range map[string]string{
		"code span":  "`a\x1b[31mb`",
		"fenced":     "```\n\x1b]0;t\x07x\n```",
		"link text":  "[a\x1b[2Jb](https://example.com)",
		"link url":   "[x](https://example.com/\x1b]52;c;x\x07)",
		"image alt":  "![a\x1b[31mb](https://example.com/i.png)",
		"summary":    "<details>\n<summary>a\x1b[31mb</summary>\n</details>",
		"bidi":       "[github.com\u202e](https://example.com)",
		"entity esc": "x &#27;[2J y",
	} {
		got := Render(body, 40)
		if strings.Contains(strip(got), "\x1b") || strings.ContainsAny(got, "\x07\u202e") {
			t.Errorf("%s: control sequence reached output: %q", name, got)
		}
	}
}

func TestRenderNeverDropsWordsWhenWrapping(t *testing.T) {
	// Tables are left out: they change shape with width by design, so their words move.
	body := "# A heading that is long enough to wrap\n\nSome **bold** and _italic_ prose with a [link text](https://example.com/a/long/path) and `code spans` too.\n\n" +
		"- first item that wraps around the edge of a narrow pane\n  - nested item that also wraps around the edge\n- [ ] a task item that wraps around\n\n" +
		"> quoted words that wrap around the edge of a narrow pane\n\n```\na long line of code that has to be hard wrapped somewhere\n```\n"
	alnum := func(s string) string {
		return strings.Map(func(r rune) rune {
			if unicode.IsLetter(r) || unicode.IsDigit(r) {
				return r
			}
			return -1
		}, strip(s))
	}
	want := alnum(Render(body, 1000))
	for _, w := range []int{20, 30, 60, 80} {
		if got := alnum(Render(body, w)); got != want {
			t.Errorf("width %d lost or reordered text:\n got %q\nwant %q", w, got, want)
		}
	}
}

func TestRenderListsAndCodeBlocks(t *testing.T) {
	tests := []struct {
		name, body, want string
	}{
		{"tight list", "- a\n- b\n", "• a\n• b"},
		{"loose list", "- a\n\n- b\n", "• a\n\n• b"},
		{"ordered list keeps its start", "3. x\n4. y\n", "3. x\n4. y"},
		{"indented code", "para\n\n    code line\n", "para\n\n  code line"},
		{"checked loose task", "- [x] a\n\n- [ ] b\n", "☑ a\n\n☐ b"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := strip(Render(tt.body, 80)); got != tt.want {
				t.Errorf("got %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRenderStripsDecodedControlCharsFromAltAndHeaders(t *testing.T) {
	for name, body := range map[string]string{
		"image alt":    "![a&#27;[2Jb](https://i.io/p.png)",
		"table header": "| a&#27;[2Jb | c&#x9b;d |\n|---|---|\n| 1 | 2 |\n",
	} {
		for _, w := range []int{80, 5} {
			if got := Render(body, w); strings.Contains(strip(got), "\x1b") || strings.ContainsRune(got, '\u009b') {
				t.Errorf("%s at %d: control sequence reached output: %q", name, w, got)
			}
		}
	}
}

func TestRenderNumberedTaskItemContinuationIndents(t *testing.T) {
	got := strip(Render("10. [ ] one two three four five six\n", 14))
	if want := "☐ one two\n  three four\n  five six"; got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRenderAutolinksAreHyperlinks(t *testing.T) {
	got := Render("<https://auto.io/a> and https://bare.io/b", 80)
	for _, u := range []string{"https://auto.io/a", "https://bare.io/b"} {
		if !strings.Contains(got, "\x1b]8;;"+u+"\x1b\\") {
			t.Errorf("no hyperlink to %s in %q", u, got)
		}
	}
	if want := "https://auto.io/a and https://bare.io/b"; strip(got) != want {
		t.Errorf("got %q, want %q", strip(got), want)
	}
}

func TestRenderDecodesEntitiesOutsideParagraphs(t *testing.T) {
	tests := []struct {
		name, body, want string
	}{
		{"heading", "# a &amp; b", "a & b"},
		{"link text", "[x &lt; y](https://e.io)", "x < y"},
		{"code span stays literal", "`&amp; \\* a  b`", `&amp; \* a b`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := strip(Render(tt.body, 80)); got != tt.want {
				t.Errorf("got %q, want %q", got, tt.want)
			}
		})
	}
}
